[package]
name = "gadgets-scfs"
description = "Solana Cluster Feature Sets"
repository = "https://github.com/FrankC01/solana-gadgets/tree/main/rust"
categories = ["command-line-utilities", "solana"]
version = "0.2.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"
semver = "1.0"
solana-client = { git = "https://github.com/nitro-svm/agave.git", branch = "remove-zstd-rpc-client" }
solana-sdk = { git = "https://github.com/nitro-svm/agave.git", branch = "remove-zstd-rpc-client" }
thiserror = "1.0"

[dev-dependencies]
tokio = { version = "1.38", features = ["test-util", "macros"] }
